packages:
  - "packages/*"
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@windsland52/maa-log-adapter@1.1.0'
  - '@windsland52/maa-log-kernel@1.0.2'
  - '@windsland52/maa-log-parser@1.1.0'
  - '@windsland52/maa-log-runtime@1.1.0'
  - '@windsland52/maa-log-tools@1.3.0'
